Fix releasenote for opendaylight support
The use of ':' is revered by reno for a special reason.
This is causing the following error:

Exception occurred:
   File "/home/zuul/.venv/local/lib/python2.7/site-packages/yaml/scanner.py", line 576, in fetch_value
     self.get_mark())
 ScannerError: mapping values are not allowed here
   in "<string>", line 8, column 41:
      ... versions are currently supported: Nitrogen and Oxygen.

Change-Id: Ib0962adef6eb75e9dd7b819695f4f93518ff20c4
(cherry picked from commit 02a96b9a7d89b0daea736a04510113dda12f7292)